export enum SavedListActionTypes {
  GET_SAVED_LIST = 'SAVED_LIST/GET_SAVED_LIST',
  GET_ONE_SAVED_LIST = 'SAVED_LIST/GET_ONE_SAVED_LIST',
  UPDATE_SAVED_LIST = 'SAVED_LIST/UPDATE_SAVED_LIST',
  DELETE_SAVED_LIST = 'SAVED_LIST/DELETE_SAVED_LIST',
  CREATE_SAVED_LIST = 'SAVED_LIST/CREATE_SAVED_LIST',
}
