export enum CompaniesActionTypes {
  GET_FAVORITES = 'COMPANIES/GET_FAVORITES',
  GET_COMPANIES = 'COMPANIES/GET_COMPANIES',
  LIKE_COMPANY = 'COMPANIES/LIKE_COMPANY',
  DELETE_FROM_FAVORITES = 'COMPANIES/DELETE_FROM_FAVORITES',
}
